Support URI to swagger schema with custom url
adeo/ingress-autoswagger pull request #23
Opened 2022-04-07 08:40 UTC by Split174

1. removed binding to art.lmru in Dockerfile
2. support custom location to swagger schema with maintaining backwards compatibility

Motivation:
Not all services have a v3/api-docs path to the swagger, for example, NestJS uses {apiUrl}-json https://github.com/nestjs/swagger/blob/master/lib/swagger-module.ts#L81

In the future, I propose to get rid of the hardcode of the version, extension and api-docs of the url

2022-04-07 13:27 UTC, voborgus requested changes

2022-04-07 13:27 UTC, voborgus commented on README.md
> +* **SWAGGER_JSON_URI** can be null, path to swagger schema
Description should be like:

*`Optional, default: null`* Array includes all possible paths to the [Open API JSON](https://swagger.io/specification/) specifications. This value will rewrite standard URL pattern `/{version}/api-docs` and will ignore **VERSIONS** and **APIDOCS_EXTENSION** values.

2022-04-07 13:27 UTC, voborgus commented on README.md
> +* **SWAGGER_JSON_URI** can be null, path to swagger schema
In addition, I advice to rename this variable to something like `OPENAPI_PATHS` since this links leads to [Open API JSON](https://swagger.io/specification/) specifications, not to SWAGGER specification. And this variable is list; so it should be in plural form.

2022-04-07 13:27 UTC, voborgus commented on README.md
> +* **SWAGGER_JSON_URI** can be null, path to swagger schema
Also, please insert one sentence about this variable please to 10th line of the readme file

2022-04-07 13:30 UTC, voborgus commented
Agree on `I propose to get rid of the hardcode of the version, extension and api-docs of the url`

Should we mark the old variables as deprecated to start to notice people about the future change?

2022-04-08 11:05 UTC, Split174 commented
@voborgus I took note of the comments. Added a message about obsolete environment variables, updated the readme and changed the naming

2022-04-08 14:49 UTC, voborgus requested changes
Thanks for your commits! Last comments and this PR will be ready to merge.

P.S. Could you also bump the version in the `https://github.com/adeo/ingress-autoswagger/blob/master/helm/values.yaml` file please?

2022-04-08 14:49 UTC, voborgus commented on README.md
>  For example:
for example duplicated

2022-04-08 14:49 UTC, voborgus commented on ingress-autoswagger.go
> +		log.Println("OpenApi Paths URI:", swaggerJsons)
could you move this log line to the previous "if" block, please?

2022-04-08 17:52 UTC, voborgus commented
By the way, looking at https://github.com/adeo/ingress-autoswagger/issues/13 and next idea comes to my mind:
should we specify the full list of services with their domains rather than their paths in this variable. So I mean replace

```bash
SERVICES="[\"plaster-calculator\",\"product-binder\"]" OPENAPI_PATHS="[\"api-json\",\"v2/swagger.json\",\"v2/swagger.yaml\"]" go run ingress-autoswagger.go
```

with

```bash
OPENAPI_URLS="[\"https://plaster-calculator/api-json\",\"http://product-binder/v2/swagger.json\",\"http://service3/v2/swagger.yaml\"]" go run ingress-autoswagger.go
```

WDYT? @Split174

2022-04-20 15:16 UTC, merged